name: 'Start all microservices'
description: 'Use this action to start all Python Italia services'

inputs:
  postgres-port:
    description: 'Postgres port'
    required: true
  start-frontend-services:
    description: 'Set to true to start FE services'
    required: false
    default: "false"

outputs:
  association-backend-url:
    description: "Association backend service URL"
    value: ${{ steps.association-backend-startup.outputs.url }}
  users-backend-url:
    description: "Association backend service URL"
    value: ${{ steps.users-backend-startup.outputs.url }}
  pycon-backend-url:
    description: "Association backend service URL"
    value: ${{ steps.pycon-backend-startup.outputs.url }}

runs:
  using: "composite"

  steps:
    - name: Install backend dependencies
      shell: bash
      run: |
        echo "::group::Install dependencies"
        echo backend:users-backend:association-backend | rush -D ":" 'cd ./{1} && poetry install'
        echo "::endgroup::"

    - name: Install frontend dependencies
      shell: bash
      run: |
        if "${{ inputs.start-frontend-services }}" == "true"; then
          echo "::group::Install dependencies"
          echo frontend:association-frontend | rush -D ":" 'cd ./{1} && yarn install --network-concurrency 8'
          echo "::endgroup::"
        fi

    - name: Start PyCon Backend
      id: pycon-backend-startup
      shell: bash
      working-directory: ./backend
      run: |
        echo "::group::Start PyCon Backend"
        GITHUB_ACTIONS=true \
        CI=true \
        DATABASE_URL=psql://postgres:postgres@localhost:${{ inputs.postgres-port }}/postgres  \
        FRONTEND_URL=x  \
        ALLOWED_HOSTS='*' \
        DEBUG=False \
        DJANGO_SETTINGS_MODULE=pycon.settings.dev \
        poetry run python manage.py runserver 0.0.0.0:8000 &
        echo "::endgroup::"

        echo "::set-output name=url::http://localhost:8000"

    - name: Start Users Backend
      id: users-backend-startup
      shell: bash
      working-directory: ./users-backend
      run: |
        echo "::group::Start Users Backend"

        GITHUB_ACTIONS=true \
        CI=true \
        DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:${{ inputs.postgres-port }}/postgres \
        IDENTITY_SECRET=xx \
        PASTAPORTO_SECRET=x \
        ASSOCIATION_FRONTEND_URL=x \
        SECRET_KEY=x \
        poetry run task server &

        echo "::endgroup::"

        echo "::set-output name=url::http://localhost:8050"

    - name: Start Association Backend
      shell: bash
      id: association-backend-startup
      working-directory: ./association-backend
      run: |
        echo "::group::Start Association Backend"

        GITHUB_ACTIONS=true \
        CI=true \
        DATABASE_URL=postgresql://postgres:postgres@localhost:${{ inputs.postgres-port }}/postgres \
        ASSOCIATION_FRONTEND_URL=xx \
        STRIPE_SECRET_API_KEY=xx \
        STRIPE_SUBSCRIPTION_PRICE_ID=x \
        STRIPE_WEBHOOK_SIGNATURE_SECRET=x \
        PASTAPORTO_SECRET=x \
        poetry run task server &

        echo "::endgroup::"

        echo "::set-output name=url::http://localhost:8060"

    # FE
    - name: Start PyCon Frontend
      shell: bash
      id: pycon-frontend-startup
      working-directory: ./frontend
      run: |
        echo "::group::Start PyCon Frontend"

        GITHUB_ACTIONS=true yarn dev &

        echo "::endgroup::"

        echo "::set-output name=url::http://localhost:3000"
