name: Deploy

concurrency: deploy-${{ fromJSON('["pastaporto", "production"]')[github.ref == 'refs/heads/main'] }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the environment you want to deploy"
        default: "pastaporto"
        required: true
      services:
        description: 'Comma-separated list of services to deploy. Use "all" to deploy all.'
        default: "all"
        required: false

env:
  # ALL_SERVICES: '[
  #     { "name": "pycon-backend", "dir": "backend" },
  #     { "name": "association-backend", "dir": "association-backend" },
  #     { "name": "association-backend", "dir": "association-backend" },
  #     { "name": "gateway", "dir": "gateway" },
  #   ]'
  ALL_SERVICES: '[
      { "name": "gateway", "dir": "gateway" }
    ]'

jobs:
  services:
    runs-on: ubuntu-latest
    outputs:
      services-matrix: ${{ steps.services.outputs.services-matrix }}
      services-names: ${{ steps.services.outputs.services-names }}
      environment: ${{ steps.services.outputs.environment }}
    steps:
      - name: Prepare services to deploy
        id: services
        shell: python
        run: |
          import os
          import json

          with open(os.environ['GITHUB_EVENT_PATH']) as json_file:
            github_event = json.load(json_file)

          event_input = github_event.get('inputs', {})
          # TODO Replace with production
          environment = event_input.get('environment', 'test')
          requested_services = event_input.get('services', 'all')

          all_services = json.loads(os.environ['ALL_SERVICES'])
          allowed_services = [service['name'] for service in all_services]

          if requested_services == 'all':
            requested_services = allowed_services
          else:
            requested_services = requested_services.split(',')

          matrix = {
            "service": []
          }
          for requested_service in requested_services:
            if requested_service not in allowed_services:
              raise ValueError(f"Invalid service: {requested_service}")

            service_data = next(
              (service for service in all_services if service['name'] == requested_service),
            )
            matrix['service'].append(service_data)

          print(f'::set-output name=services-matrix::{json.dumps(json.dumps(matrix))}')
          print(f'::set-output name=services-names::{json.dumps(requested_services)}')
          print(f'::set-output name=environment::"{environment}"')
  # build-and-publish-services:
  #   needs: [services]
  #   uses: pythonitalia/pycon/.github/workflows/deploy.build-and-publish-services.yml@WEB-159-new-deployment-pipeline
  #   with:
  #     services: ${{fromJSON(needs.services.outputs.services-matrix)}}
  #   secrets:
  #     aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform:
    # needs: [services, build-and-publish-services]
    needs: [services]
    uses: pythonitalia/pycon/.github/workflows/deploy.terraform.yml@WEB-159-new-deployment-pipeline
    with:
      environment: "pastaporto"
      services: ${{ fromJSON(needs.services.outputs.services-names) }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
